### ISSUE TITLE
Support getting Result via module's name

### ISSUE THREAD

**Issue by jamebs** [NeuroSYS-pl/magda#11]
### What?
I'd like to get/check results by module's name (currently supported are only *exposed name* and reference to python classes).

### Why?
To cover more cases of using `Module.ResultSet`

### How?
Example:
```yml
modules:
- name: module-a1
  type: ModuleA

- name: module-a2
  type: ModuleA

- name: module-b
  type: ModuleB
  parameters:
    ref: module-a1
  depends_on:
  - module-a1
  - module-a2
```

```python
@accepts(ModuleA)
@register('ModuleB')
@finalize
class ModuleB(Module.Runtime):
    def run(self, data: Module.ResultSet, *args, **kwargs):
        ref = self.parameters.get('ref')  # := module-a1
        ...
        # Currently:
        x = next((d.result for d in data.collection if d.name == ref))
        # It should be:
        x = data.get(ref)
        ...
```
