### ISSUE TITLE
Optional expose parameter added to module's config

### ISSUE THREAD

**Issue by DanielPopek** [NeuroSYS-pl/magda#14]
**What?**
I'd like to optionally determine if a module is exposed or not in YAML config. This setting should override the configuration in decorator (if such exists).

**Why?**
The modification should increase the reusability of modules, that could be used in some pipelines as exposable and in another as non-exposable. 

**How?**
By adding _expose_ field to YAML config and by parsing it in ConfigReader. _Expose_ should accept a boolean or a string with a concrete name. 

**Examples:**

```yml
modules:
- name: module-a1
  type: ModuleA
  expose: partial-results

- name: module-b1
  type: ModuleA
  depends_on:
  - module-a1
```

or

```yml
modules:
- name: module-a1
  type: ModuleA
  expose: True

- name: module-b1
  type: ModuleA
  depends_on:
  - module-a1
```

should have higher priority than:
```py
@accepts(ModuleA)
@register('ModuleB')
@expose('articles')
@finalize
class ModuleB(Module.Runtime):
   ...
```
